function: 'olympus.baselines.bio_pMHC_task2.main'

medians: ['random_state']

objective: 'validation_aac'

variables:
    random_state: 1
    bootstrap_seed: 1

defaults: {}

params:
        hidden_layer_sizes: 121
        alpha: 0.45
