function: 'olympus.baselines.logreg.main'

objective: 'validation_error_rate'

var_name: 'random_state'

variables:
    random_state: 1
    bootstrap_seed: 1

defaults: {}

fidelity: null

space:
    C: 'uniform(0, 1)'
    l1_ratio: 'uniform(0, 1)'
