variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    OLYMPUS_DATA_PATH: "$CI_PROJECT_DIR/data"

cache:
  paths:
    - .cache/pip
    - olympe/
    - data/

stages:
  - tests

job doc:
  image: ubuntu
  stage: tests
  script:
    - apt install python3-pip
    - python3.6 -m venv --system-site-packages olympe
    - . olympe/bin/activate
    - pip install -e .
    - pip install -r requirements.txt
    - pip install -r docs/requirements.txt
    - make travis-doc

# CPU testing
job generic-tests:
  image: ubuntu
  tags:
    - ubuntu
  stage: tests
  script:
    - apt update
    - apt install python3-pip
    - python3.6 -m venv --system-site-packages olympe
    - . olympe/bin/activate
    - make travis-install
    - make travis-unit
    - make travis-custom
    - make travis-minimalist
    - make travis-hpo_simple
    - make travis-classification
    - make travis-end

# nvidia-docker is a pain to setup
#job nvidia-tests:
#  image: pytorch/pytorch:latest
#  tags:
#    - nvidia
#  stage: tests
#  script:
#    - python3.6 -m venv --system-site-packages olympe
#    - . olympe/bin/activate
#    - make travis-install
#    - make travis-unit
#    - make travis-custom
#    - make travis-minimalist
#    - make travis-hpo_simple
#    - make travis-classification
#    - make travis-classification-fp16
#    - make travis-end


#  --device=/dev/kfd --device=/dev/dri --group-add video
job rocm-tests:
  image: rocm/pytorch:rocm2.9_ubuntu18.04_py3.6
  tags:
    - rocm
  stage: tests
  script:
    - ln -f /usr/bin/python3.6 /usr/bin/python3
    - ln -f /usr/bin/python3.6 /usr/bin/python
    - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    - python get-pip.py
    - make travis-install
    - make travis-unit
    - make travis-custom
    - make travis-minimalist
    - make travis-hpo_simple
    - make travis-classification
    - make travis-classification-fp16
    - make travis-end
