# Use NVIDIA/CPU as default
# Do not specify the image so the worker will use the default one
# specified in the worker config
# default:
#   image: pytorch/pytorch:latest
#        : rocm/pytorch:rocm2.9_ubuntu18.04_py3.6
#        : ubuntu

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/../.cache/pip"
    OLYMPUS_DATA_PATH: "$CI_PROJECT_DIR/../data"

cache:
  paths:
    - ../.cache/pip
    - ../olympe/
    - ../data

stages:
  - install
  - tests
  - finish

# Clean - Ubuntu
# - apt install python3-pip
# - pip3 install virtualenv

job dependencies:
  stage: install
  script:
    - python3.6 -m venv --system-site-packages ../olympe
    - . ../olympe/bin/activate
    - make travis-install

job unit:
  stage: tests
  script:
    - . venv/bin/olympe
    - make travis-unit

job custom:
  stage: tests
  script:
    - . venv/bin/olympe
    - make travis-custom

job minimalist:
  stage: tests
  script:
    - . venv/bin/olympe
    - make travis-minimalist

job hpo-simple:
  stage: tests
  script:
    - . venv/bin/olympe
    - make travis-hpo_simple

job classification:
  stage: tests
  script:
    - . venv/bin/olympe
    - make travis-classification

#job classification-fp16:
#  stage: tests
#  script:
#    - . venv/bin/activate
#    - make travis-classification-fp16

job doc:
  stage: tests
  script:
    - . venv/bin/olympe
    - make travis-doc

job upload-coverage:
  stage: finish
  script:
    - . venv/bin/olympe
    - make travis-end
