# Use NVIDIA/CPU as default
# Do not specify the image so the worker will use the default one
# specified in the worker config
default:
  image: pytorch/pytorch:latest
#        : rocm/pytorch:rocm2.9_ubuntu18.04_py3.6
#        : ubuntu

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    OLYMPUS_DATA_PATH: "$CI_PROJECT_DIR/data"

cache:
  paths:
    - .cache/pip
    - olympe/
    - data/
    - .coverage*

stages:
  - install
  - tests
  - finish

# Clean - Ubuntu
# - apt install python3-pip
# - pip3 install virtualenv

job dependencies:
  stage: install
  script:
    - python3.6 -m venv --system-site-packages olympe
    - . olympe/bin/activate
    - make travis-install

job doc:
  stage: tests
  script:
    - . olympe/bin/activate
    - make travis-doc

job unit:
  stage: tests
  script:
    - . olympe/bin/activate
    - make travis-unit
    - make travis-custom
    - make travis-minimalist
    - make travis-hpo_simple
    - make travis-classification
    - make travis-end

#job classification-fp16:
#  stage: tests
#  script:
#    - . venv/bin/activate
#    - make travis-classification-fp16
