# Use NVIDIA/CPU as default
default:
  image: pytorch/pytorch:latest

stages:
  - install
  - tests
  - finish

job 0:
  stage: install
  script: make travis-install

job 1:
  stage: tests
  script:
    - make travis-unit
    - make travis-custom
    - make travis-minimalist
    - make travis-hpo_simple
    - make travis-classification
    - make travis-classification-fp16
    - make travis-end
    - make travis-doc

