language: python

python:
  - "3.7"

install:
  - pip install -r requirements.txt
  - pip install -e .

jobs:
  include:
    - stage: doc
      script:
        - pip install -r docs/requirements.txt
        - make travis-doc
    - stage: unit-test
      script:
        - pip install -r tests/requirements.txt
        - python -m pytest --cov=olympus tests/unit
        - python -m pytest --cov-append --cov=olympus tests/integration
        - codecov
    - stage: minimalist
      script:
        - make travis-minimalist
    - stage: hpo
      script:
        - make travis-hpo_simple
    - stage: classification
      script:
        - make travis-classification
