language: python

python:
  - "3.7"

install:
  - pip install -e .

jobs:
  include:
    - stage: demo-test
      script:
        - make check
        - make hpo
        - make run-examples
        - make build-doc
