language: python

cache: pip

python:
  - "3.7"

install:
  - apt-get install mongodb-server libeigen3-dev swig
  - make travis-install

jobs:
  include:
    - stage: doc
      script:
        - make travis-doc
    - stage: unit-test
      script:
        - export OLYMPUS_PROGRESS_FREQUENCY_EPOCH=0
        - export OLYMPUS_PROGRESS_FREQUENCY_BATCH=0
        - make travis-unit
        - make travis-minimalist
        - make travis-custom
        - make travis-hpo_simple
        - make travis-classification
        - make travis-end
