language: python

python:
  - "3.7"

install:
  - pip install -e .
  - pip install -r requirements.txt
  - pip install -r docs/requirements.txt
  - pip install -r tests/requirements.txt

jobs:
  include:
    - stage: doc
      script:
        - make travis-doc
    - stage: unit-test
      script:
        - make travis-unit
        - make travis-minimalist
        - make travis-custom
        - make travis-hpo_simple
        - make travis-classification
        - make travis-end
