from olympus.dashboard.queue_pages.inspect import InspectQueue
from olympus.dashboard.queue_pages.fanova_viz import FANVOAQueue
from olympus.dashboard.queue_pages.gantt import GanttQueue
from olympus.dashboard.queue_pages.metric import MetricQueue
from olympus.dashboard.queue_pages.result import ResultQueue
from olympus.dashboard.queue_pages.space_exploration import SpaceQueue
from olympus.dashboard.queue_pages.status import StatusQueue
from olympus.dashboard.queue_pages.log import LogsQueue
from olympus.dashboard.queue_pages.metric import MetricQueue
