version: 2
jobs:
  build:
    branches:
      only:
        - resume_testing

    docker:
      - image: circleci/python:3.7.5

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "setup.py" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make travis-install

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run tests!
      - run:
          name: run doc
          command: |
            . venv/bin/activate
            make travis-doc

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            make travis-unit

      - run:
          name: run custom
          command: |
            . venv/bin/activate
            make travis-custom

      - run:
          name: run minimalist
          command: |
            . venv/bin/activate
            make travis-minimalist

      - run:
          name: run hpo
          command: |
            . venv/bin/activate
            make travis-hpo_simple

      - run:
          name: run classification
          command: |
            . venv/bin/activate
            make travis-classification

      - run:
          name: run end
          command: |
            . venv/bin/activate
            make travis-end

      - store_artifacts:
          path: test-reports
          destination: test-reports
