function: 'olympus.baselines.bio_pMHC_task.main'

medians: ['random_state']

objective: 'mean_validation_aac'

variables:
    random_state: 1
    bootstrap_seed: 1

defaults: {}

params:
        hidden_layer_sizes: 54
        alpha: 0.3
