function: 'olympus.baselines.bio_pMHC_task.main'

objective: 'mean_validation_aac'

variables:
    random_state: 1
    bootstrap_seed: 1

resumable: 0

defaults: {}

params:
        hidden_layer_sizes: 54
        alpha: 0.3
