function: 'olympus.baselines.vgg11_cifar10.main'

objective: 'validation_error_rate'

variables:
    init_seed: 1
    bootstrapping_seed: 2
    transform_seed: 3
    sampler_seed: 4

resumable: 1

defaults:
    half: True
    epoch: 10

params:
    learning_rate: 0.1
    momentum: 0.9
    weight_decay: 0.0001
    gamma: 0.98
