function: 'olympus.baselines.tiny.main'

objective: 'validation_error_rate'

variables:
    random_state: 1
    bootstrap_seed: 1

resumable: 0

defaults: {}

params:
    max_depth: 10
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0
