name: tests

on:
  push:
    branches:
      - master
  pull_request:
    types: [synchronize]

jobs:
  olympus-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: cache-pip
      uses: actions/cache@v1
      with:
        path: venv
        key: ${{ runner.OS }}-build-${{ hashFiles('setup.py') }}
        restore-keys: |
          ${{ runner.OS }}-build-${{ env.cache-name }}-
          ${{ runner.OS }}-build-
          ${{ runner.OS }}-

    - name: Install dependencies
      run: |
        sudo apt-get install mongodb-server
        python -m pip install --upgrade pip
        pip install virtualenv
        python -m venv venv
        . venv/bin/activate
        pip uninstall -y msgqueue orion sspace
        make travis-install
        pip install flake8

    - name: Lint with flake8
      run: |
        . venv/bin/activate
        # stop the build if there are Python syntax errors or undefined names
        flake8 olympus --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 olympus --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: unit
      run: |
        . venv/bin/activate
        make travis-unit

    - name: api-test
      run: |
        . venv/bin/activate
        make travis-custom

    - name: minimalist
      run: |
        . venv/bin/activate
        make travis-minimalist

    - name: no-hpo
      run: |
        . venv/bin/activate
        make travis-classification-config

    - name: hpo-simple
      run: |
        . venv/bin/activate
        make travis-hpo_simple

    - name: hpo-parallel
      run: |
        . venv/bin/activate
        make travis-hpo_parallel

    - name: classification
      run: |
        . venv/bin/activate
        make travis-classification

    - name: upload-coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        . venv/bin/activate
        make travis-end
