name: tests

on: [push]

env:
    OLYMPUS_PROGRESS_SHOW_METRICS: none
    OLYMPUS_PROGRESS_FREQUENCY_EPOCH: 0
    OLYMPUS_PROGRESS_FREQUENCY_BATCH: 0

jobs:
  olympus-ci:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: cache-pip
      uses: actions/cache@v1
      with:
        path: ~/unittest_env
        key: ${{ runner.OS }}-build-${{ hashFiles('setup.py') }}-${{ hashFiles('**/requirements.txt') }}

    - name: Install dependencies
      run: |
        sudo apt-get install mongodb-server libeigen3-dev swig
        python -m pip install --upgrade pip
        pip install virtualenv
        python -m venv ~/unittest_env
        source ~/unittest_env/bin/activate
        pip uninstall -y msgqueue orion sspace sklearn
        make travis-install
        pip install flake8

    - name: Lint with flake8
      run: |
        source ~/unittest_env/bin/activate
        # stop the build if there are Python syntax errors or undefined names
        # flake8 olympus --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 olympus --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: unit
      run: |
        source ~/unittest_env/bin/activate
        make travis-unit

    - name: api-test
      run: |
        source ~/unittest_env/bin/activate
        make travis-custom

    - name: minimalist
      run: |
        source ~/unittest_env/bin/activate
        make travis-minimalist

    - name: no-hpo
      run: |
        source ~/unittest_env/bin/activate
        make travis-classification-config

    - name: hpo-simple
      run: |
        source ~/unittest_env/bin/activate
        make travis-hpo_simple

    - name: hpo-parallel
      run: |
        source ~/unittest_env/bin/activate
        make travis-hpo_parallel

    - name: classification
      run: |
        source ~/unittest_env/bin/activate
        make travis-classification

    - name: upload-coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        source ~/unittest_env/bin/activate
        make travis-end
